### PR TITLE
Remove CRUD

### PR DESCRIPTION
**Pull request by thehabes**
Getting rid of anything that communicates with RERUM for CRUDing.  Query is available without the need for a token or agent.  
No more login-logout
etc.

### CODE REVIEW

**Comment by cubap** [comment]
Not to put too fine a point, you don't need any Java at all for this part. It is completely readonly and just needs to know the collection names and generator id to filter for, which isn't private information.

**Comment by thehabes** [comment]
Yeah, I am playing around with how it works with just laving `/query` alive to make sure load stuff and click stuff does what I expect in the read only situations.  If it performs right, then we can pull that stuff out of the back end that uses the generatorID (agentID) and use it through DEER attributes or script or whatever to filter.  DEER is already using the collection names correctly so no changes there, it is exposed as an attribute.

**Comment by thehabes** [comment]
image

Nope.  A couple more things to unpack haha

**Comment by thehabes** [comment]
https://centerfordigitalhumanities.github.io/Lived-Religion-STL/web/all_experiences.html is the `no-more-CRUD` branch if you want to play along.

**Pull request merged**
